In [2]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd

In [3]:
#getting Data Locs
#import os
#for dirname, _, filenames in os.walk('/kaggle/input'):
#    for filename in filenames:
#        print(os.path.join(dirname, filename))

In [4]:
# Importing the data
data_train = pd.read_csv('train.csv')
data_test = pd.read_csv('Test.csv')
#dataset=pd.concat([data_train,data_test])

In [5]:
#dataset['SalePrice']

In [6]:
data_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
# Number of columns in data 
columns=data_train.columns
columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [8]:
# Count of null values
data_train.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       177
LotArea             0
Street              0
Alley             956
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          6
MasVnrArea          6
ExterQual           0
ExterCond           0
Foundation          0
                 ...
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       488
GarageType         58
GarageYrBlt        58
GarageFinish       58
GarageCars          0
GarageArea          0
GarageQual         58
GarageCond         58
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1019
Fence             827
MiscFeature       978
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
Length: 81, dtype: int64

In [9]:
# Summary of Data
data_train.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1021.000000,1021.000000,844.000000,1021.000000,1021.000000,1021.000000,1021.000000,1021.000000,1015.000000,1021.000000,...,1021.000000,1021.000000,1021.000000,1021.000000,1021.000000,1021.000000,1021.000000,1021.000000,1021.000000,1021.000000
mean,511.000000,56.973555,69.792654,10657.963761,6.119491,5.576885,1971.611166,1985.201763,108.132020,442.067581,...,96.996082,47.204701,21.636631,3.626836,15.117532,1.136141,44.450539,6.310480,2007.833497,181701.220372
std,294.881615,42.251561,23.157942,11312.704443,1.383879,1.111091,30.026796,20.444483,187.415923,442.087912,...,123.758771,67.571851,60.747712,30.600346,55.339646,25.833746,520.052102,2.687768,1.323133,79892.871027
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1880.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,256.000000,20.000000,59.750000,7540.000000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,130000.000000
50%,511.000000,50.000000,70.000000,9452.000000,6.000000,5.000000,1974.000000,1994.000000,0.000000,380.000000,...,0.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163500.000000
75%,766.000000,70.000000,80.000000,11639.000000,7.000000,6.000000,2001.000000,2004.000000,173.000000,719.000000,...,171.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,215000.000000
max,1021.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,2260.000000,...,857.000000,523.000000,552.000000,508.000000,410.000000,648.000000,15500.000000,12.000000,2010.000000,755000.000000

In [10]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 81 columns):
Id               1021 non-null int64
MSSubClass       1021 non-null int64
MSZoning         1021 non-null object
LotFrontage      844 non-null float64
LotArea          1021 non-null int64
Street           1021 non-null object
Alley            65 non-null object
LotShape         1021 non-null object
LandContour      1021 non-null object
Utilities        1021 non-null object
LotConfig        1021 non-null object
LandSlope        1021 non-null object
Neighborhood     1021 non-null object
Condition1       1021 non-null object
Condition2       1021 non-null object
BldgType         1021 non-null object
HouseStyle       1021 non-null object
OverallQual      1021 non-null int64
OverallCond      1021 non-null int64
YearBuilt        1021 non-null int64
YearRemodAdd     1021 non-null int64
RoofStyle        1021 non-null object
RoofMatl         1021 non-null object
Exterior1st      1021 non-null object
Exterior2nd      1021 non-null object
MasVnrType       1015 non-null object
MasVnrArea       1015 non-null float64
ExterQual        1021 non-null object
ExterCond        1021 non-null object
Foundation       1021 non-null object
BsmtQual         995 non-null object
BsmtCond         995 non-null object
BsmtExposure     994 non-null object
BsmtFinType1     995 non-null object
BsmtFinSF1       1021 non-null int64
BsmtFinType2     994 non-null object
BsmtFinSF2       1021 non-null int64
BsmtUnfSF        1021 non-null int64
TotalBsmtSF      1021 non-null int64
Heating          1021 non-null object
HeatingQC        1021 non-null object
CentralAir       1021 non-null object
Electrical       1021 non-null object
1stFlrSF         1021 non-null int64
2ndFlrSF         1021 non-null int64
LowQualFinSF     1021 non-null int64
GrLivArea        1021 non-null int64
BsmtFullBath     1021 non-null int64
BsmtHalfBath     1021 non-null int64
FullBath         1021 non-null int64
HalfBath         1021 non-null int64
BedroomAbvGr     1021 non-null int64
KitchenAbvGr     1021 non-null int64
KitchenQual      1021 non-null object
TotRmsAbvGrd     1021 non-null int64
Functional       1021 non-null object
Fireplaces       1021 non-null int64
FireplaceQu      533 non-null object
GarageType       963 non-null object
GarageYrBlt      963 non-null float64
GarageFinish     963 non-null object
GarageCars       1021 non-null int64
GarageArea       1021 non-null int64
GarageQual       963 non-null object
GarageCond       963 non-null object
PavedDrive       1021 non-null object
WoodDeckSF       1021 non-null int64
OpenPorchSF      1021 non-null int64
EnclosedPorch    1021 non-null int64
3SsnPorch        1021 non-null int64
ScreenPorch      1021 non-null int64
PoolArea         1021 non-null int64
PoolQC           2 non-null object
Fence            194 non-null object
MiscFeature      43 non-null object
MiscVal          1021 non-null int64
MoSold           1021 non-null int64
YrSold           1021 non-null int64
SaleType         1021 non-null object
SaleCondition    1021 non-null object
SalePrice        1021 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 646.2+ KB

In [11]:
#Extracting nan columns
nan=data_train.isna().sum()
na=pd.DataFrame([np.array(columns),np.array(nan)]).T
na.columns=['columns','nan_sum']
nan_columns=na[na['nan_sum']!=0]['columns'].to_numpy()
nan_columns

array(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature'],
      dtype=object)

In [12]:
len(nan_columns)

18

In [13]:
#columns with numeric type
nan_flt=['LotFrontage','MasVnrArea','GarageYrBlt']

In [14]:
data_train[nan_flt].isna().sum()

LotFrontage    177
MasVnrArea       6
GarageYrBlt     58
dtype: int64

In [15]:
data_train[nan_flt]

      LotFrontage  MasVnrArea  GarageYrBlt
0            65.0       196.0       2003.0
1            80.0         0.0       1976.0
2            68.0       162.0       2001.0
3            60.0         0.0       1998.0
4            84.0       350.0       2000.0
5            85.0         0.0       1993.0
6            75.0       186.0       2004.0
7             NaN       240.0       1973.0
8            51.0         0.0       1931.0
9            50.0         0.0       1939.0
10           70.0         0.0       1965.0
11           85.0       286.0       2005.0
12            NaN         0.0       1962.0
13           91.0       306.0       2006.0
14            NaN       212.0       1960.0
15           51.0         0.0       1991.0
16            NaN       180.0       1970.0
17           72.0         0.0       1967.0
18           66.0         0.0       2004.0
19           70.0         0.0       1958.0
20          101.0       380.0       2005.0
21           57.0         0.0       1930.0
22           75.0       281.0       2002.0
23           44.0         0.0       1976.0
24            NaN         0.0       1968.0
25          110.0       640.0       2007.0
26           60.0         0.0       2005.0
27           98.0       200.0       2008.0
28           47.0         0.0       1957.0
29           60.0         0.0       1920.0
...           ...         ...          ...
991         121.0         0.0       1925.0
992          80.0       340.0       1964.0
993          68.0         0.0       2005.0
994          96.0       230.0       2008.0
995          51.0         0.0       1946.0
996           NaN         0.0       1961.0
997           NaN       571.0       1970.0
998          60.0         0.0       1922.0
999          64.0        24.0       2006.0
1000         74.0         0.0       1956.0
1001         60.0         0.0       1920.0
1002         75.0        53.0       2006.0
1003          NaN       164.0       1976.0
1004         43.0        16.0       2005.0
1005         65.0       220.0       1977.0
1006          NaN         0.0       1970.0
1007         21.0         0.0       1970.0
1008         43.0       108.0       2004.0
1009         60.0         0.0          NaN
1010        115.0         0.0       1948.0
1011         75.0         0.0          NaN
1012         55.0         0.0       1923.0
1013         60.0         0.0       1956.0
1014         60.0       206.0       1948.0
1015         70.0         0.0       2001.0
1016         73.0       196.0       1996.0
1017          NaN         0.0       1984.0
1018          NaN        76.0       1991.0
1019         43.0       145.0       2005.0
1020         60.0         0.0       2005.0

[1021 rows x 3 columns]

In [16]:
#extracting floating type and handling missing vals

#from missingpy import KNNImputer
#imputer =KNNImputer(n_neighbors=2)
#data_train[nan_flt]=imputer.fit_transform(data_train[nan_flt])
# Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean')
imputer = imputer.fit(data_train[nan_flt])
data_train[nan_flt] = imputer.transform(data_train[nan_flt])
data_train[nan_flt].isna().sum()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

LotFrontage    0
MasVnrArea     0
GarageYrBlt    0
dtype: int64

In [17]:
data_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.000000,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.000000,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.000000,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.000000,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.000000,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.000000,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.000000,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,69.792654,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.000000,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.000000,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000
10,11,20,RL,70.000000,11200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,129500
11,12,60,RL,85.000000,11924,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,New,Partial,345000
12,13,20,RL,69.792654,12968,Pave,NaN,IR2,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,144000
13,14,20,RL,91.000000,10652,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,279500
14,15,20,RL,69.792654,10920,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000
15,16,45,RM,51.000000,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000
16,17,20,RL,69.792654,11241,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72.000000,10791,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66.000000,13695,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,159000
19,20,20,RL,70.000000,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000
20,21,60,RL,101.000000,14215,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2006,New,Partial,325300
21,22,45,RM,57.000000,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,NaN,GdPrv,NaN,0,6,2007,WD,Normal,139400
22,23,20,RL,75.000000,9742,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,230000
23,24,120,RM,44.000000,4224,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,129900
24,25,20,RL,69.792654,8246,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,154000
25,26,20,RL,110.000000,14230,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,256300
26,27,20,RL,60.000000,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,134800
27,28,20,RL,98.000000,11478,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,306000
28,29,20,RL,47.000000,16321,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2006,WD,Normal,207500
29,30,30,RM,60.000000,6324,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,992,70,RM,121.000000,17671,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2009,WD,Normal,168000
992,993,60,RL,80.000000,9760,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnWw,NaN,0,7,2007,WD,Normal,187000
993,994,60,RL,68.000000,8846,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2006,New,Partial,173900
994,995,20,RL,96.000000,12456,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,337500
995,996,50,RL,51.000000,4712,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,8,2006,WD,Abnorml,121600
996,997,20,RL,69.792654,10659,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2006,COD,Normal,136500
997,998,20,RL,69.792654,11717,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2009,WD,Normal,185000
998,999,30,RM,60.000000,9786,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,WD,Normal,91000
999,1000,20,RL,64.000000,6762,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2010,WD,Normal,206000
1000,1001,20,RL,74.000000,10206,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,82000
1001,1002,30,RL,60.000000,5400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2007,WD,Abnorml,86000
1002,1003,20,RL,75.000000,11957,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,232000
1003,1004,90,RL,69.792654,11500,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,136905
1004,1005,120,RL,43.000000,3182,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,181000
1005,1006,80,RL,65.000000,8385,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2008,WD,Normal,149900
1006,1007,20,RL,69.792654,12155,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2007,WD,Normal,163500
1007,1008,160,RM,21.000000,2217,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2009,WD,Normal,88000
1008,1009,20,RL,43.000000,12118,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,240000
1009,1010,50,RL,60.000000,6000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,102000
1010,1011,50,RL,115.000000,21286,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2008,WD,Normal,135000
1011,1012,90,RL,75.000000,9825,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,100000
1012,1013,70,RL,55.000000,10592,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,165000
1013,1014,30,RM,60.000000,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,85000
1014,1015,20,RL,60.000000,11664,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,119200
1015,1016,60,RL,70.000000,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2009,WD,Normal,227000
1016,1017,20,RL,73.000000,11883,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,203000
1017,1018,120,RL,69.792654,5814,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2009,COD,Abnorml,187500
1018,1019,80,RL,69.792654,10784,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,160000
1019,1020,120,RL,43.000000,3013,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,213490
1020,1021,20,RL,60.000000,7024,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,176000

In [18]:
data_train[nan_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 18 columns):
LotFrontage     1021 non-null float64
Alley           65 non-null object
MasVnrType      1015 non-null object
MasVnrArea      1021 non-null float64
BsmtQual        995 non-null object
BsmtCond        995 non-null object
BsmtExposure    994 non-null object
BsmtFinType1    995 non-null object
BsmtFinType2    994 non-null object
FireplaceQu     533 non-null object
GarageType      963 non-null object
GarageYrBlt     1021 non-null float64
GarageFinish    963 non-null object
GarageQual      963 non-null object
GarageCond      963 non-null object
PoolQC          2 non-null object
Fence           194 non-null object
MiscFeature     43 non-null object
dtypes: float64(3), object(15)
memory usage: 143.7+ KB

In [19]:
nan_flt

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [20]:
nan_columns

array(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish',
       'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature'],
      dtype=object)

In [21]:
#getting object types and handing nan vals
nan_obj=np.setdiff1d(nan_columns,nan_flt)
nan_obj

array(['Alley', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'BsmtQual', 'Fence', 'FireplaceQu', 'GarageCond',
       'GarageFinish', 'GarageQual', 'GarageType', 'MasVnrType',
       'MiscFeature', 'PoolQC'], dtype=object)

In [22]:
data_train[nan_obj].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 15 columns):
Alley           65 non-null object
BsmtCond        995 non-null object
BsmtExposure    994 non-null object
BsmtFinType1    995 non-null object
BsmtFinType2    994 non-null object
BsmtQual        995 non-null object
Fence           194 non-null object
FireplaceQu     533 non-null object
GarageCond      963 non-null object
GarageFinish    963 non-null object
GarageQual      963 non-null object
GarageType      963 non-null object
MasVnrType      1015 non-null object
MiscFeature     43 non-null object
PoolQC          2 non-null object
dtypes: object(15)
memory usage: 119.7+ KB

In [23]:
#handing nan vals
for n_obj in nan_obj:
    data_train[n_obj].fillna('null', inplace = True)

In [24]:
data_train[nan_obj].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 15 columns):
Alley           1021 non-null object
BsmtCond        1021 non-null object
BsmtExposure    1021 non-null object
BsmtFinType1    1021 non-null object
BsmtFinType2    1021 non-null object
BsmtQual        1021 non-null object
Fence           1021 non-null object
FireplaceQu     1021 non-null object
GarageCond      1021 non-null object
GarageFinish    1021 non-null object
GarageQual      1021 non-null object
GarageType      1021 non-null object
MasVnrType      1021 non-null object
MiscFeature     1021 non-null object
PoolQC          1021 non-null object
dtypes: object(15)
memory usage: 119.7+ KB

In [25]:
#we had Handled missing data till here
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 81 columns):
Id               1021 non-null int64
MSSubClass       1021 non-null int64
MSZoning         1021 non-null object
LotFrontage      1021 non-null float64
LotArea          1021 non-null int64
Street           1021 non-null object
Alley            1021 non-null object
LotShape         1021 non-null object
LandContour      1021 non-null object
Utilities        1021 non-null object
LotConfig        1021 non-null object
LandSlope        1021 non-null object
Neighborhood     1021 non-null object
Condition1       1021 non-null object
Condition2       1021 non-null object
BldgType         1021 non-null object
HouseStyle       1021 non-null object
OverallQual      1021 non-null int64
OverallCond      1021 non-null int64
YearBuilt        1021 non-null int64
YearRemodAdd     1021 non-null int64
RoofStyle        1021 non-null object
RoofMatl         1021 non-null object
Exterior1st      1021 non-null object
Exterior2nd      1021 non-null object
MasVnrType       1021 non-null object
MasVnrArea       1021 non-null float64
ExterQual        1021 non-null object
ExterCond        1021 non-null object
Foundation       1021 non-null object
BsmtQual         1021 non-null object
BsmtCond         1021 non-null object
BsmtExposure     1021 non-null object
BsmtFinType1     1021 non-null object
BsmtFinSF1       1021 non-null int64
BsmtFinType2     1021 non-null object
BsmtFinSF2       1021 non-null int64
BsmtUnfSF        1021 non-null int64
TotalBsmtSF      1021 non-null int64
Heating          1021 non-null object
HeatingQC        1021 non-null object
CentralAir       1021 non-null object
Electrical       1021 non-null object
1stFlrSF         1021 non-null int64
2ndFlrSF         1021 non-null int64
LowQualFinSF     1021 non-null int64
GrLivArea        1021 non-null int64
BsmtFullBath     1021 non-null int64
BsmtHalfBath     1021 non-null int64
FullBath         1021 non-null int64
HalfBath         1021 non-null int64
BedroomAbvGr     1021 non-null int64
KitchenAbvGr     1021 non-null int64
KitchenQual      1021 non-null object
TotRmsAbvGrd     1021 non-null int64
Functional       1021 non-null object
Fireplaces       1021 non-null int64
FireplaceQu      1021 non-null object
GarageType       1021 non-null object
GarageYrBlt      1021 non-null float64
GarageFinish     1021 non-null object
GarageCars       1021 non-null int64
GarageArea       1021 non-null int64
GarageQual       1021 non-null object
GarageCond       1021 non-null object
PavedDrive       1021 non-null object
WoodDeckSF       1021 non-null int64
OpenPorchSF      1021 non-null int64
EnclosedPorch    1021 non-null int64
3SsnPorch        1021 non-null int64
ScreenPorch      1021 non-null int64
PoolArea         1021 non-null int64
PoolQC           1021 non-null object
Fence            1021 non-null object
MiscFeature      1021 non-null object
MiscVal          1021 non-null int64
MoSold           1021 non-null int64
YrSold           1021 non-null int64
SaleType         1021 non-null object
SaleCondition    1021 non-null object
SalePrice        1021 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 646.2+ KB

In [26]:
data_train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.000000,8450,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,2,2008,WD,Normal,208500
1,2,20,RL,80.000000,9600,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,5,2007,WD,Normal,181500
2,3,60,RL,68.000000,11250,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,9,2008,WD,Normal,223500
3,4,70,RL,60.000000,9550,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.000000,14260,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,12,2008,WD,Normal,250000
5,6,50,RL,85.000000,14115,Pave,null,IR1,Lvl,AllPub,...,0,null,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.000000,10084,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,8,2007,WD,Normal,307000
7,8,60,RL,69.792654,10382,Pave,null,IR1,Lvl,AllPub,...,0,null,null,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.000000,6120,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.000000,7420,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,1,2008,WD,Normal,118000
10,11,20,RL,70.000000,11200,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,2,2008,WD,Normal,129500
11,12,60,RL,85.000000,11924,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,7,2006,New,Partial,345000
12,13,20,RL,69.792654,12968,Pave,null,IR2,Lvl,AllPub,...,0,null,null,null,0,9,2008,WD,Normal,144000
13,14,20,RL,91.000000,10652,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,8,2007,New,Partial,279500
14,15,20,RL,69.792654,10920,Pave,null,IR1,Lvl,AllPub,...,0,null,GdWo,null,0,5,2008,WD,Normal,157000
15,16,45,RM,51.000000,6120,Pave,null,Reg,Lvl,AllPub,...,0,null,GdPrv,null,0,7,2007,WD,Normal,132000
16,17,20,RL,69.792654,11241,Pave,null,IR1,Lvl,AllPub,...,0,null,null,Shed,700,3,2010,WD,Normal,149000
17,18,90,RL,72.000000,10791,Pave,null,Reg,Lvl,AllPub,...,0,null,null,Shed,500,10,2006,WD,Normal,90000
18,19,20,RL,66.000000,13695,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,6,2008,WD,Normal,159000
19,20,20,RL,70.000000,7560,Pave,null,Reg,Lvl,AllPub,...,0,null,MnPrv,null,0,5,2009,COD,Abnorml,139000
20,21,60,RL,101.000000,14215,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,11,2006,New,Partial,325300
21,22,45,RM,57.000000,7449,Pave,Grvl,Reg,Bnk,AllPub,...,0,null,GdPrv,null,0,6,2007,WD,Normal,139400
22,23,20,RL,75.000000,9742,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,9,2008,WD,Normal,230000
23,24,120,RM,44.000000,4224,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,6,2007,WD,Normal,129900
24,25,20,RL,69.792654,8246,Pave,null,IR1,Lvl,AllPub,...,0,null,MnPrv,null,0,5,2010,WD,Normal,154000
25,26,20,RL,110.000000,14230,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,7,2009,WD,Normal,256300
26,27,20,RL,60.000000,7200,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,5,2010,WD,Normal,134800
27,28,20,RL,98.000000,11478,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,5,2010,WD,Normal,306000
28,29,20,RL,47.000000,16321,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,12,2006,WD,Normal,207500
29,30,30,RM,60.000000,6324,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,5,2008,WD,Normal,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,992,70,RM,121.000000,17671,Pave,Grvl,Reg,Lvl,AllPub,...,0,null,null,null,0,11,2009,WD,Normal,168000
992,993,60,RL,80.000000,9760,Pave,null,Reg,Lvl,AllPub,...,0,null,MnWw,null,0,7,2007,WD,Normal,187000
993,994,60,RL,68.000000,8846,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,8,2006,New,Partial,173900
994,995,20,RL,96.000000,12456,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,7,2009,WD,Normal,337500
995,996,50,RL,51.000000,4712,Pave,null,IR1,Lvl,AllPub,...,0,null,MnPrv,null,0,8,2006,WD,Abnorml,121600
996,997,20,RL,69.792654,10659,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,1,2006,COD,Normal,136500
997,998,20,RL,69.792654,11717,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,2,2009,WD,Normal,185000
998,999,30,RM,60.000000,9786,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,5,2006,WD,Normal,91000
999,1000,20,RL,64.000000,6762,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,2,2010,WD,Normal,206000
1000,1001,20,RL,74.000000,10206,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,7,2009,WD,Normal,82000
1001,1002,30,RL,60.000000,5400,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,1,2007,WD,Abnorml,86000
1002,1003,20,RL,75.000000,11957,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,7,2008,WD,Normal,232000
1003,1004,90,RL,69.792654,11500,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,6,2007,WD,Normal,136905
1004,1005,120,RL,43.000000,3182,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,5,2009,WD,Normal,181000
1005,1006,80,RL,65.000000,8385,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,11,2008,WD,Normal,149900
1006,1007,20,RL,69.792654,12155,Pave,null,IR3,Lvl,AllPub,...,0,null,null,null,0,3,2007,WD,Normal,163500
1007,1008,160,RM,21.000000,2217,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,8,2009,WD,Normal,88000
1008,1009,20,RL,43.000000,12118,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,4,2009,WD,Normal,240000
1009,1010,50,RL,60.000000,6000,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,6,2006,WD,Normal,102000
1010,1011,50,RL,115.000000,21286,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,8,2008,WD,Normal,135000
1011,1012,90,RL,75.000000,9825,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,5,2010,WD,Normal,100000
1012,1013,70,RL,55.000000,10592,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,8,2007,WD,Normal,165000
1013,1014,30,RM,60.000000,7200,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,6,2009,WD,Normal,85000
1014,1015,20,RL,60.000000,11664,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,11,2007,WD,Normal,119200
1015,1016,60,RL,70.000000,8400,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,11,2009,WD,Normal,227000
1016,1017,20,RL,73.000000,11883,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,6,2009,WD,Normal,203000
1017,1018,120,RL,69.792654,5814,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,8,2009,COD,Abnorml,187500
1018,1019,80,RL,69.792654,10784,Pave,null,IR1,Lvl,AllPub,...,0,null,null,null,0,5,2007,WD,Normal,160000
1019,1020,120,RL,43.000000,3013,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,4,2006,WD,Normal,213490
1020,1021,20,RL,60.000000,7024,Pave,null,Reg,Lvl,AllPub,...,0,null,null,null,0,6,2008,WD,Normal,176000

In [27]:
num_d=['Id','MSSubClass','LotFrontage','LotArea','OverallQual','OverallCond','YearBuilt',
'YearRemodAdd','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF',
'1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','BsmtFullBath','BsmtHalfBath',
'FullBath','HalfBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd','Fireplaces',
'GarageYrBlt','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch',
'3SsnPorch','ScreenPorch','PoolArea','MiscVal','MoSold','YrSold','SalePrice']

In [28]:
columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [29]:
#getting columns which have categorical data
cat_d=np.setdiff1d(columns,num_d)
cat_d

array(['Alley', 'BldgType', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'BsmtQual', 'CentralAir', 'Condition1',
       'Condition2', 'Electrical', 'ExterCond', 'ExterQual',
       'Exterior1st', 'Exterior2nd', 'Fence', 'FireplaceQu', 'Foundation',
       'Functional', 'GarageCond', 'GarageFinish', 'GarageQual',
       'GarageType', 'Heating', 'HeatingQC', 'HouseStyle', 'KitchenQual',
       'LandContour', 'LandSlope', 'LotConfig', 'LotShape', 'MSZoning',
       'MasVnrType', 'MiscFeature', 'Neighborhood', 'PavedDrive',
       'PoolQC', 'RoofMatl', 'RoofStyle', 'SaleCondition', 'SaleType',
       'Street', 'Utilities'], dtype=object)

In [30]:
#Encoding Categorical Data

data_train=pd.get_dummies(data=data_train, columns=cat_d,drop_first=True)

In [31]:

col=data_train.columns
Xx=np.setdiff1d(col,['SalePrice'])

In [32]:
X=data_train[Xx]
y=pd.DataFrame(data_train['SalePrice'])

In [33]:
#X=pd.DataFrame(X)
len(X.columns)

249

In [34]:
data_train.shape

(1021, 250)

### till this point we had handled missing data and categorical data 
### X and y variables are ready

# ============================================

## Building optimal model by Backward elimination
## Extracting useful features

In [35]:
import statsmodels.api as sm
X=np.append(arr=np.ones((1021,1)).astype(int),values=X,axis=1)

In [36]:
high=1.0
feat=np.arange(249)
while high>0.045:
    X_opt=X[:,feat]
    regressor_Ols=sm.OLS(endog=y,exog=X_opt).fit()
    results_summary=regressor_Ols.summary()
    # Note that tables is a list. The table at index 1 is the "core" table. Additionally, read_html puts dfs in a list, so we want index 0
    results_as_html = results_summary.tables[1].as_html()
    fin_res=pd.read_html(results_as_html, header=0, index_col=0)[0]
    fin_res=fin_res.drop(columns=['coef','std err','t','[0.025','0.975]'])
    high=fin_res.loc[fin_res['P>|t|'].idxmax()][0]
    fin_res=fin_res.reset_index(level=0)
    feat=pd.DataFrame(feat)
    fin_res=pd.concat([fin_res,feat],axis=1)
    fin_res.drop(fin_res.loc[fin_res['P>|t|']==high].index, inplace=True)
    fin_res=fin_res.rename(columns={0:'feat'})
    feat=np.array(fin_res['feat'])

In [37]:
feat.shape
#feat=feat.reshape(-1,1)

(62,)

In [38]:
test_feat=Xx[feat]
#test_ft=np.setdiff1d(test_feat,cols_test)
#test_feat=np.setdiff1d(test_feat,test_ft)

In [39]:
#from sklearn import ensemble
#GBoost = ensemble.GradientBoostingRegressor(n_estimators = 3000, max_depth = 5,max_features='sqrt',
#                                            min_samples_split = 10,learning_rate = 0.005,loss = 'huber',
 #                                           min_samples_leaf=15,random_state =10)
#GBoost.fit(data_train[test_feat], y)

In [40]:
#y_pred = GBoost.predict(data_test[test_feat])

In [41]:
# Fitting Multiple Linear Regression to the Training set using extracted features
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(data_train[test_feat], y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score


# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(data_train[test_feat], y, test_size = 0.4, random_state = 0)


# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Predicting the Test set results
y_pred = regressor.predict(X_test)
#print("gives R2 score",r2_score(y_pred,y_test))
#print('gives MSE is:',mean_squared_error(y_test, y_pred))
rms = np.sqrt(mean_squared_error(y_test, y_pred))
print('gives RMSE is:',rms)

gives RMSE is: 36529.00099651655

In [43]:
len(feat)

62

In [46]:
#!pip install statsmodels --upgrade
high

0.044000000000000004

## Looking into test set data

In [47]:
# Importing the data
data_test = pd.read_csv('Test.csv')

In [48]:
data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 80 columns):
Id               439 non-null int64
MSSubClass       439 non-null int64
MSZoning         439 non-null object
LotFrontage      357 non-null float64
LotArea          439 non-null int64
Street           439 non-null object
Alley            26 non-null object
LotShape         439 non-null object
LandContour      439 non-null object
Utilities        439 non-null object
LotConfig        439 non-null object
LandSlope        439 non-null object
Neighborhood     439 non-null object
Condition1       439 non-null object
Condition2       439 non-null object
BldgType         439 non-null object
HouseStyle       439 non-null object
OverallQual      439 non-null int64
OverallCond      439 non-null int64
YearBuilt        439 non-null int64
YearRemodAdd     439 non-null int64
RoofStyle        439 non-null object
RoofMatl         439 non-null object
Exterior1st      439 non-null object
Exterior2nd      439 non-null object
MasVnrType       437 non-null object
MasVnrArea       437 non-null float64
ExterQual        439 non-null object
ExterCond        439 non-null object
Foundation       439 non-null object
BsmtQual         428 non-null object
BsmtCond         428 non-null object
BsmtExposure     428 non-null object
BsmtFinType1     428 non-null object
BsmtFinSF1       439 non-null int64
BsmtFinType2     428 non-null object
BsmtFinSF2       439 non-null int64
BsmtUnfSF        439 non-null int64
TotalBsmtSF      439 non-null int64
Heating          439 non-null object
HeatingQC        439 non-null object
CentralAir       439 non-null object
Electrical       438 non-null object
1stFlrSF         439 non-null int64
2ndFlrSF         439 non-null int64
LowQualFinSF     439 non-null int64
GrLivArea        439 non-null int64
BsmtFullBath     439 non-null int64
BsmtHalfBath     439 non-null int64
FullBath         439 non-null int64
HalfBath         439 non-null int64
BedroomAbvGr     439 non-null int64
KitchenAbvGr     439 non-null int64
KitchenQual      439 non-null object
TotRmsAbvGrd     439 non-null int64
Functional       439 non-null object
Fireplaces       439 non-null int64
FireplaceQu      237 non-null object
GarageType       416 non-null object
GarageYrBlt      416 non-null float64
GarageFinish     416 non-null object
GarageCars       439 non-null int64
GarageArea       439 non-null int64
GarageQual       416 non-null object
GarageCond       416 non-null object
PavedDrive       439 non-null object
WoodDeckSF       439 non-null int64
OpenPorchSF      439 non-null int64
EnclosedPorch    439 non-null int64
3SsnPorch        439 non-null int64
ScreenPorch      439 non-null int64
PoolArea         439 non-null int64
PoolQC           5 non-null object
Fence            87 non-null object
MiscFeature      11 non-null object
MiscVal          439 non-null int64
MoSold           439 non-null int64
YrSold           439 non-null int64
SaleType         439 non-null object
SaleCondition    439 non-null object
dtypes: float64(3), int64(34), object(43)
memory usage: 274.5+ KB

In [49]:
columns_test=data_test.columns
#Extracting nan columns
nan_test=data_test.isna().sum()
na_test=pd.DataFrame([np.array(columns_test),np.array(nan_test)]).T
na_test.columns=['columns','nan_sum']
nan_columns_test=na_test[na_test['nan_sum']!=0]['columns'].to_numpy()
nan_columns_test

array(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence',
       'MiscFeature'], dtype=object)

In [50]:
data_test[nan_columns_test].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 19 columns):
LotFrontage     357 non-null float64
Alley           26 non-null object
MasVnrType      437 non-null object
MasVnrArea      437 non-null float64
BsmtQual        428 non-null object
BsmtCond        428 non-null object
BsmtExposure    428 non-null object
BsmtFinType1    428 non-null object
BsmtFinType2    428 non-null object
Electrical      438 non-null object
FireplaceQu     237 non-null object
GarageType      416 non-null object
GarageYrBlt     416 non-null float64
GarageFinish    416 non-null object
GarageQual      416 non-null object
GarageCond      416 non-null object
PoolQC          5 non-null object
Fence           87 non-null object
MiscFeature     11 non-null object
dtypes: float64(3), object(16)
memory usage: 65.2+ KB

In [51]:
#extracting floating type and handling missing vals
nan_flt_test=['LotFrontage','MasVnrArea','GarageYrBlt']
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean')
imputer = imputer.fit(data_test[nan_flt_test])
data_test[nan_flt_test] = imputer.transform(data_test[nan_flt_test])
data_test[nan_flt_test].isna().sum()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

LotFrontage    0
MasVnrArea     0
GarageYrBlt    0
dtype: int64

In [52]:
data_test[nan_columns_test].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 19 columns):
LotFrontage     439 non-null float64
Alley           26 non-null object
MasVnrType      437 non-null object
MasVnrArea      439 non-null float64
BsmtQual        428 non-null object
BsmtCond        428 non-null object
BsmtExposure    428 non-null object
BsmtFinType1    428 non-null object
BsmtFinType2    428 non-null object
Electrical      438 non-null object
FireplaceQu     237 non-null object
GarageType      416 non-null object
GarageYrBlt     439 non-null float64
GarageFinish    416 non-null object
GarageQual      416 non-null object
GarageCond      416 non-null object
PoolQC          5 non-null object
Fence           87 non-null object
MiscFeature     11 non-null object
dtypes: float64(3), object(16)
memory usage: 65.2+ KB

In [53]:
len(nan_columns_test)

19

In [54]:
nan_flt_test

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [55]:
#getting object types and handing nan vals
nan_obj_test=np.setdiff1d(nan_columns_test,nan_flt_test)

#handing nan vals
for n_obj in nan_obj_test:
    data_test[n_obj].fillna('null', inplace = True)

In [56]:
data_test[nan_columns_test].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 19 columns):
LotFrontage     439 non-null float64
Alley           439 non-null object
MasVnrType      439 non-null object
MasVnrArea      439 non-null float64
BsmtQual        439 non-null object
BsmtCond        439 non-null object
BsmtExposure    439 non-null object
BsmtFinType1    439 non-null object
BsmtFinType2    439 non-null object
Electrical      439 non-null object
FireplaceQu     439 non-null object
GarageType      439 non-null object
GarageYrBlt     439 non-null float64
GarageFinish    439 non-null object
GarageQual      439 non-null object
GarageCond      439 non-null object
PoolQC          439 non-null object
Fence           439 non-null object
MiscFeature     439 non-null object
dtypes: float64(3), object(16)
memory usage: 65.2+ KB

In [57]:
num_d_test=['Id','MSSubClass','LotFrontage','LotArea','OverallQual','OverallCond','YearBuilt',
'YearRemodAdd','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF',
'1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','BsmtFullBath','BsmtHalfBath',
'FullBath','HalfBath','BedroomAbvGr','KitchenAbvGr','TotRmsAbvGrd','Fireplaces',
'GarageYrBlt','GarageCars','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch',
'3SsnPorch','ScreenPorch','PoolArea','MiscVal','MoSold','YrSold']

In [58]:
columns_test

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [59]:
#getting columns which have categorical data
cat_d_test=np.setdiff1d(columns_test,num_d_test)
cat_d_test

array(['Alley', 'BldgType', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1',
       'BsmtFinType2', 'BsmtQual', 'CentralAir', 'Condition1',
       'Condition2', 'Electrical', 'ExterCond', 'ExterQual',
       'Exterior1st', 'Exterior2nd', 'Fence', 'FireplaceQu', 'Foundation',
       'Functional', 'GarageCond', 'GarageFinish', 'GarageQual',
       'GarageType', 'Heating', 'HeatingQC', 'HouseStyle', 'KitchenQual',
       'LandContour', 'LandSlope', 'LotConfig', 'LotShape', 'MSZoning',
       'MasVnrType', 'MiscFeature', 'Neighborhood', 'PavedDrive',
       'PoolQC', 'RoofMatl', 'RoofStyle', 'SaleCondition', 'SaleType',
       'Street', 'Utilities'], dtype=object)

In [60]:
#Encoding Categorical Data

data_test=pd.get_dummies(data=data_test, columns=cat_d_test,drop_first=True)
data_test.isna().sum()

Id                       0
MSSubClass               0
LotFrontage              0
LotArea                  0
OverallQual              0
OverallCond              0
YearBuilt                0
YearRemodAdd             0
MasVnrArea               0
BsmtFinSF1               0
BsmtFinSF2               0
BsmtUnfSF                0
TotalBsmtSF              0
1stFlrSF                 0
2ndFlrSF                 0
LowQualFinSF             0
GrLivArea                0
BsmtFullBath             0
BsmtHalfBath             0
FullBath                 0
HalfBath                 0
BedroomAbvGr             0
KitchenAbvGr             0
TotRmsAbvGrd             0
Fireplaces               0
GarageYrBlt              0
GarageCars               0
GarageArea               0
WoodDeckSF               0
OpenPorchSF              0
                        ..
Neighborhood_Somerst     0
Neighborhood_StoneBr     0
Neighborhood_Timber      0
Neighborhood_Veenker     0
PavedDrive_P             0
PavedDrive_Y             0
PoolQC_Fa                0
PoolQC_Gd                0
PoolQC_null              0
RoofMatl_CompShg         0
RoofMatl_Roll            0
RoofMatl_Tar&Grv         0
RoofMatl_WdShake         0
RoofMatl_WdShngl         0
RoofStyle_Gable          0
RoofStyle_Gambrel        0
RoofStyle_Hip            0
RoofStyle_Mansard        0
RoofStyle_Shed           0
SaleCondition_Alloca     0
SaleCondition_Family     0
SaleCondition_Normal     0
SaleCondition_Partial    0
SaleType_CWD             0
SaleType_ConLD           0
SaleType_ConLw           0
SaleType_New             0
SaleType_Oth             0
SaleType_WD              0
Street_Pave              0
Length: 234, dtype: int64

In [61]:
cols_test=data_test.columns

In [62]:
len(cols_test)

234

In [63]:
data_test

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SaleType_CWD,SaleType_ConLD,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,Street_Pave
0,1022,20,64.000000,7406,7,5,2006,2006,84.0,684,...,0,0,1,0,0,0,1,0,0,1
1,1023,50,52.000000,9439,5,5,1930,1950,0.0,324,...,0,1,0,0,0,0,0,0,1,1
2,1024,120,43.000000,3182,7,5,2005,2006,14.0,16,...,0,1,0,0,0,0,0,0,1,1
3,1025,20,70.658263,15498,8,6,1976,1976,0.0,1165,...,0,0,0,0,0,0,0,0,0,1
4,1026,20,70.000000,7700,5,5,1972,1972,0.0,138,...,0,1,0,0,0,0,0,0,1,1
5,1027,20,73.000000,9300,5,5,1960,1960,324.0,697,...,0,1,0,0,0,0,0,0,1,1
6,1028,20,71.000000,9520,8,5,2007,2008,338.0,1513,...,0,0,1,0,0,0,1,0,0,1
7,1029,50,79.000000,9492,5,5,1941,1950,0.0,368,...,0,1,0,0,0,0,0,0,1,1
8,1030,160,21.000000,1680,6,7,1972,1972,281.0,317,...,0,1,0,0,0,0,0,0,1,1
9,1031,190,70.658263,7082,5,8,1916,1995,0.0,0,...,0,1,0,0,0,0,0,0,1,1
10,1032,75,102.000000,15863,7,3,1920,1970,0.0,523,...,0,1,0,0,0,0,0,0,1,1
11,1033,60,70.658263,14541,8,7,1993,1993,0.0,1012,...,0,0,0,0,0,0,0,0,1,1
12,1034,20,70.658263,8125,7,5,2002,2002,295.0,986,...,0,1,0,0,0,0,0,0,1,1
13,1035,30,50.000000,6305,5,7,1938,1950,0.0,0,...,0,1,0,0,0,0,0,0,1,1
14,1036,20,70.658263,11500,4,3,1957,1957,0.0,0,...,0,1,0,0,0,0,0,0,1,1
15,1037,20,89.000000,12898,9,5,2007,2008,70.0,1022,...,0,1,0,0,0,0,0,0,1,1
16,1038,60,70.658263,9240,8,5,2001,2002,396.0,0,...,0,1,0,0,0,0,0,0,1,1
17,1039,160,21.000000,1533,4,6,1970,2008,0.0,0,...,0,1,0,0,0,0,0,0,1,1
18,1040,180,21.000000,1477,4,4,1970,1970,0.0,509,...,0,1,0,0,0,0,0,0,1,1
19,1041,20,88.000000,13125,5,4,1957,2000,67.0,168,...,0,1,0,0,0,0,0,0,1,1
20,1042,60,70.658263,9130,6,8,1966,2000,252.0,400,...,0,1,0,0,0,0,0,0,1,1
21,1043,120,34.000000,5381,6,5,2005,2005,135.0,900,...,0,1,0,0,0,0,0,0,1,1
22,1044,60,86.000000,11839,7,5,1990,1990,99.0,1085,...,0,1,0,0,0,0,0,0,1,1
23,1045,20,80.000000,9600,8,5,1981,1981,0.0,1104,...,0,1,0,0,0,0,0,0,1,1
24,1046,20,70.658263,13680,3,5,1955,1955,0.0,0,...,0,1,0,0,0,0,0,0,1,1
25,1047,60,85.000000,16056,9,5,2005,2006,208.0,240,...,0,0,1,0,0,0,1,0,0,1
26,1048,20,57.000000,9245,5,5,1994,1995,0.0,686,...,0,1,0,0,0,0,0,0,1,1
27,1049,20,100.000000,21750,5,4,1960,2006,75.0,0,...,0,1,0,0,0,0,0,0,1,1
28,1050,20,60.000000,11100,4,7,1946,2006,0.0,0,...,0,0,0,0,0,0,0,0,1,1
29,1051,20,73.000000,8993,7,5,2007,2007,0.0,0,...,0,0,1,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,1431,60,60.000000,21930,5,5,2005,2005,0.0,0,...,0,1,0,0,0,0,0,0,1,1
410,1432,120,70.658263,4928,6,6,1976,1976,0.0,958,...,0,1,0,0,0,0,0,0,1,1
411,1433,30,60.000000,10800,4,6,1927,2007,0.0,0,...,0,1,0,0,0,0,0,0,1,1
412,1434,60,93.000000,10261,6,5,2000,2000,318.0,0,...,0,1,0,0,0,0,0,0,1,1
413,1435,20,80.000000,17400,5,5,1977,1977,0.0,936,...,0,1,0,0,0,0,0,0,1,1
414,1436,20,80.000000,8400,6,9,1962,2005,237.0,0,...,0,0,0,0,0,0,0,0,0,1
415,1437,20,60.000000,9000,4,6,1971,1971,0.0,616,...,0,1,0,0,0,0,0,0,1,1
416,1438,20,96.000000,12444,8,5,2008,2008,426.0,1336,...,0,0,1,0,0,0,1,0,0,1
417,1439,20,90.000000,7407,6,7,1957,1996,0.0,600,...,0,1,0,0,0,0,0,0,1,1
418,1440,60,80.000000,11584,7,6,1979,1979,96.0,315,...,0,1,0,0,0,0,0,0,1,1
419,1441,70,79.000000,11526,6,7,1922,1994,0.0,0,...,0,1,0,0,0,0,0,0,1,1
420,1442,120,70.658263,4426,6,5,2004,2004,147.0,697,...,0,1,0,0,0,0,0,0,1,1
421,1443,60,85.000000,11003,10,5,2008,2008,160.0,765,...,0,1,0,0,0,0,0,0,1,1
422,1444,30,70.658263,8854,6,6,1916,1950,0.0,0,...,0,1,0,0,0,0,0,0,1,1
423,1445,20,63.000000,8500,7,5,2004,2004,106.0,0,...,0,1,0,0,0,0,0,0,1,1
424,1446,85,70.000000,8400,6,5,1966,1966,0.0,187,...,0,1,0,0,0,0,0,0,1,1
425,1447,20,70.658263,26142,5,7,1962,1962,189.0,593,...,0,1,0,0,0,0,0,0,1,1
426,1448,60,80.000000,10000,8,5,1995,1996,438.0,1079,...,0,1,0,0,0,0,0,0,1,1
427,1449,50,70.000000,11767,4,7,1910,2000,0.0,0,...,0,1,0,0,0,0,0,0,1,1
428,1450,180,21.000000,1533,5,7,1970,1970,0.0,553,...,0,0,0,0,0,0,0,0,1,1
429,1451,90,60.000000,9000,5,5,1974,1974,0.0,0,...,0,1,0,0,0,0,0,0,1,1
430,1452,20,78.000000,9262,8,5,2008,2009,194.0,0,...,0,0,1,0,0,0,1,0,0,1
431,1453,180,35.000000,3675,5,5,2005,2005,80.0,547,...,0,1,0,0,0,0,0,0,1,1
432,1454,20,90.000000,17217,5,5,2006,2006,0.0,0,...,0,0,0,0,0,0,0,0,1,1
433,1455,20,62.000000,7500,7,5,2004,2005,0.0,410,...,0,1,0,0,0,0,0,0,1,1
434,1456,60,62.000000,7917,6,5,1999,2000,0.0,0,...,0,1,0,0,0,0,0,0,1,1
435,1457,20,85.000000,13175,6,6,1978,1988,119.0,790,...,0,1,0,0,0,0,0,0,1,1
436,1458,70,66.000000,9042,7,9,1941,2006,0.0,275,...,0,1,0,0,0,0,0,0,1,1
437,1459,20,68.000000,9717,5,6,1950,1996,0.0,49,...,0,1,0,0,0,0,0,0,1,1
438,1460,20,75.000000,9937,5,6,1965,1965,0.0,830,...,0,1,0,0,0,0,0,0,1,1

In [64]:
#test_feat=Xx[feat]
test_ft=np.setdiff1d(test_feat,cols_test)
test_feat=np.setdiff1d(test_feat,test_ft)

In [65]:
len(test_feat)

54

In [66]:
# Fitting Multiple Linear Regression to the Training set using extracted features
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(data_train[test_feat], y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [67]:
# Predicting the Test set results
y_pred = regressor.predict(data_test[test_feat])

In [68]:
y_pred

array([[212011.72283791],
       [100069.3863551 ],
       [193797.56544789],
       [290544.69625073],
       [123773.79697463],
       [143369.20493136],
       [280432.49569395],
       [109259.89182876],
       [136313.98587243],
       [135678.23372657],
       [241059.78827441],
       [322910.32086516],
       [235961.84044665],
       [125314.80068802],
       [ 93446.09784233],
       [316088.75552504],
       [232962.79638524],
       [100650.96440373],
       [ 53597.59224632],
       [174142.37796565],
       [174413.87013203],
       [204422.65093163],
       [237729.81029195],
       [302043.99871363],
       [124315.05584176],
       [394706.61539045],
       [132551.69703285],
       [169517.32190521],
       [122703.67296038],
       [213651.55447854],
       [217507.74177495],
       [189834.49036868],
       [173457.19552243],
       [235057.28385555],
       [175906.18981018],
       [225193.67216273],
       [273203.63084305],
       [352399.20529667],
       [217132.88680644],
       [212413.3573119 ],
       [ 79536.02321058],
       [137736.01184336],
       [138943.78309289],
       [166761.54313159],
       [258478.13819657],
       [171908.09214315],
       [176907.85820448],
       [163418.39278763],
       [127477.13517237],
       [116346.90248056],
       [168177.03716043],
       [140716.21360557],
       [143426.30155715],
       [200774.41456436],
       [171179.97590431],
       [152277.95353563],
       [144952.06861978],
       [131290.37936729],
       [123926.08987951],
       [175649.64733121],
       [128940.54246543],
       [204363.67112999],
       [151196.96250185],
       [157243.17700582],
       [153052.63083194],
       [ 82307.8268962 ],
       [258973.21030463],
       [167883.5808002 ],
       [205362.13539184],
       [ 79667.66726159],
       [166758.01621999],
       [166653.70445019],
       [164380.93562188],
       [114487.72022853],
       [188099.7464601 ],
       [148856.48628574],
       [197194.21328676],
       [ 82603.42993176],
       [197622.11418826],
       [ 26425.47842253],
       [114879.5515561 ],
       [124605.32179752],
       [143028.44697994],
       [110830.67379743],
       [330922.13229481],
       [200473.03730874],
       [277409.01553421],
       [172361.46660351],
       [307186.88398153],
       [170195.43150343],
       [206326.63829777],
       [ 98783.1153897 ],
       [137249.64798401],
       [107218.67546482],
       [348531.95006859],
       [202891.78492219],
       [136503.76391829],
       [120358.37097348],
       [117003.42705319],
       [144779.78725444],
       [240895.31546329],
       [ 89113.64716825],
       [ 98086.77965416],
       [177070.37532352],
       [103520.85703891],
       [207379.58338474],
       [230158.73664322],
       [209988.23060561],
       [106148.7717713 ],
       [130385.20989702],
       [133990.98346276],
       [143987.23929384],
       [235813.22305449],
       [183144.93403098],
       [116713.70813411],
       [131474.13456861],
       [110346.45400843],
       [192014.61660607],
       [108355.8173403 ],
       [110575.25124207],
       [176386.36107708],
       [307064.85758547],
       [105614.51035984],
       [ 85148.65262051],
       [126933.83398174],
       [172840.84590932],
       [166115.39249957],
       [103654.08365091],
       [146594.56737801],
       [118855.72577246],
       [169217.09653513],
       [228204.15790469],
       [133717.83908654],
       [221502.42307678],
       [180687.0052002 ],
       [152799.0849247 ],
       [228873.6699467 ],
       [267852.69837987],
       [187261.63367534],
       [158602.66467652],
       [215288.81891146],
       [121475.75641979],
       [160292.07453083],
       [178169.31793856],
       [264116.29787281],
       [256090.51286977],
       [175479.00647763],
       [176910.37683505],
       [461343.53079989],
       [141562.58588248],
       [153338.95081574],
       [168614.55851526],
       [229032.732605  ],
       [186516.28764091],
       [335188.13236317],
       [124379.31905338],
       [118054.1742261 ],
       [124943.40535168],
       [ 89286.17333664],
       [208027.44260182],
       [274307.35394455],
       [444065.78993771],
       [113554.30035106],
       [165177.47214292],
       [117292.77623716],
       [137951.40327782],
       [284430.56200115],
       [195721.03099021],
       [194656.38632476],
       [210352.1386966 ],
       [205638.84625563],
       [112018.18127982],
       [163751.0850965 ],
       [149041.3439298 ],
       [177502.35667541],
       [240136.76972054],
       [133709.10635769],
       [197362.83523047],
       [139064.66134234],
       [105410.45966748],
       [187430.79406383],
       [110453.65404679],
       [215539.5183742 ],
       [153523.93658974],
       [278008.31700838],
       [ 90800.83303433],
       [207714.76152752],
       [139420.29611776],
       [306372.28863701],
       [201065.88800045],
       [223687.92451485],
       [ 74495.78240747],
       [ 99341.61425985],
       [119278.94051786],
       [113035.05691782],
       [155730.24467312],
       [241864.48899956],
       [ 46697.48196451],
       [127428.00781389],
       [112989.57187528],
       [124654.93896396],
       [152073.23718096],
       [157979.31314819],
       [210095.45330001],
       [121767.34295765],
       [233847.21254877],
       [137180.78647125],
       [374604.98974999],
       [118921.14840635],
       [231486.10348612],
       [126404.87602699],
       [104935.46099218],
       [133211.96974342],
       [123266.32378698],
       [154173.18324854],
       [211404.38554207],
       [211779.55924526],
       [190206.97095107],
       [257406.81857692],
       [210212.97321625],
       [247329.30308244],
       [177243.66907923],
       [403767.86421358],
       [209037.19188799],
       [171848.50220465],
       [203635.98706473],
       [164535.01104925],
       [150191.12211749],
       [112998.74689177],
       [285404.10283788],
       [220301.34688814],
       [110558.69710968],
       [258403.8194116 ],
       [198933.10030558],
       [121296.01367459],
       [319119.46308242],
       [101470.78008772],
       [189225.08114188],
       [168114.8608342 ],
       [193110.23833982],
       [113009.22312171],
       [127591.87727509],
       [152448.97467426],
       [155082.87211158],
       [175072.81708302],
       [172622.23215173],
       [359468.61828355],
       [311969.60861672],
       [133826.14307668],
       [189282.22354832],
       [181600.40970088],
       [125053.53478364],
       [188817.02087559],
       [133439.80993197],
       [167856.73323907],
       [162070.05845325],
       [227648.53309588],
       [233770.28483612],
       [ 97989.6554122 ],
       [211018.02383868],
       [182405.82077425],
       [154361.61832502],
       [175298.01039444],
       [191210.67194082],
       [119687.63750208],
       [182740.65921789],
       [233492.91227115],
       [244330.48619216],
       [347021.547908  ],
       [129517.29438625],
       [112449.57088107],
       [142300.15515518],
       [185879.65280182],
       [121999.84502558],
       [124976.84370911],
       [135428.13561036],
       [132946.13826434],
       [621109.78308561],
       [167137.46310805],
       [243220.23824745],
       [129323.31243718],
       [300750.53046334],
       [231791.16407724],
       [161756.88062118],
       [333945.30052482],
       [232050.98150538],
       [131594.02267686],
       [148622.52752504],
       [169467.32629826],
       [269415.73441223],
       [208245.35201838],
       [324639.67773391],
       [338917.59784025],
       [ 91843.36350985],
       [207573.30498728],
       [313939.91288337],
       [213286.45127197],
       [266186.66244791],
       [ 86822.63962708],
       [181846.58531791],
       [ 52139.43905962],
       [259827.02997163],
       [ 84685.32860557],
       [291618.78751848],
       [ 66902.6369715 ],
       [ 89092.83249432],
       [131603.57129421],
       [159382.13089205],
       [194365.87552408],
       [261223.98949847],
       [133859.89993846],
       [101065.70395002],
       [136342.16436247],
       [126024.78332882],
       [173141.29837568],
       [188640.45946339],
       [ 67071.93905008],
       [215164.17631943],
       [118276.30922233],
       [116791.15230066],
       [174062.63665515],
       [234861.46561025],
       [174685.53701316],
       [217119.7179863 ],
       [ 77663.92045129],
       [254724.717225  ],
       [297108.80046364],
       [213909.06977325],
       [156685.82624733],
       [235489.89059449],
       [165274.80106899],
       [132232.82335909],
       [368928.30571328],
       [216444.59463697],
       [187204.67892059],
       [100784.52705051],
       [169287.10890678],
       [164991.3195734 ],
       [356647.25197149],
       [165015.99703741],
       [263720.52360907],
       [124908.36734092],
       [171467.14278691],
       [157168.74968944],
       [199128.98498919],
       [199520.34421613],
       [100377.08050077],
       [132336.41293761],
       [257959.93365074],
       [ 88996.95982757],
       [180354.30532296],
       [211638.05294765],
       [461822.72629873],
       [235573.14929501],
       [260652.45992521],
       [118518.29400883],
       [128239.16538328],
       [119080.21124501],
       [146620.38650358],
       [ 70460.33772629],
       [207447.6265125 ],
       [182728.00985821],
       [175670.19948881],
       [115542.31227582],
       [113392.72622392],
       [260593.63738218],
       [169766.56696436],
       [348891.63764652],
       [123677.19305216],
       [212350.98403847],
       [157672.85825589],
       [112339.57625525],
       [160287.78663584],
       [207439.30292268],
       [249154.48832416],
       [155254.11470533],
       [157604.05236954],
       [147611.89442799],
       [176525.0564001 ],
       [113668.11418354],
       [172877.54072254],
       [212188.66731376],
       [252831.52770817],
       [ 77045.40619609],
       [259449.53088108],
       [126806.31591429],
       [104971.79856725],
       [ 98555.50282398],
       [210817.93438888],
       [201701.32606715],
       [154357.29809231],
       [ 94142.47252341],
       [265719.86572849],
       [188581.9419559 ],
       [207971.36912714],
       [130302.54106526],
       [325276.98882088],
       [148710.70661871],
       [217025.44694457],
       [162631.72658169],
       [126085.16253737],
       [125271.12736505],
       [199234.24350932],
       [130354.01944897],
       [182413.93454729],
       [262528.7353368 ],
       [131468.94869576],
       [111381.11141676],
       [203578.9777609 ],
       [168499.36893522],
       [128120.85756189],
       [ 94316.78299118],
       [185046.97613966],
       [157746.75239191],
       [209629.72575169],
       [ 97262.04644065],
       [361949.95359804],
       [146592.64049977],
       [168828.87894015],
       [222965.41539006],
       [124726.64971073],
       [342525.09408211],
       [111906.94088401],
       [209973.69403388],
       [138510.07229702],
       [148638.81621218],
       [247842.07262635],
       [133097.50161442],
       [109886.55470027],
       [152400.85825151],
       [299066.14502024],
       [105193.99253211],
       [140721.51898148],
       [198904.03183768],
       [172939.07182001],
       [204744.29442197],
       [207408.92041165],
       [150796.44386519],
       [159868.45359115]])

In [69]:
SalePrice=pd.DataFrame(y_pred)
SalePrice[0].abs()
Id=data_test['Id']
submission=pd.concat([pd.DataFrame(Id),SalePrice.astype(int)],axis=1)
submission=submission.rename(columns={0:'SalePrice'})
submission.to_csv('DavidSubmission.csv',index=False)